# coding: utf-8
#
# Copyright (c) 2021 Target Brands, Inc. All rights reserved.

"""
    Vela server

    API for the Vela server  # noqa: E501

    OpenAPI spec version: 0.6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela
from vela.vela.steps_api import StepsApi  # noqa: E501
from vela.rest import ApiException


class TestStepsApi(unittest.TestCase):
    """StepsApi unit test stubs"""

    def setUp(self):
        self.api = StepsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_step(self):
        """Test case for create_step

        """
        pass

    def test_create_step_log(self):
        """Test case for create_step_log

        """
        pass

    def test_delete_step(self):
        """Test case for delete_step

        """
        pass

    def test_delete_step_log(self):
        """Test case for delete_step_log

        """
        pass

    def test_get_step(self):
        """Test case for get_step

        """
        pass

    def test_get_step_log(self):
        """Test case for get_step_log

        """
        pass

    def test_get_steps(self):
        """Test case for get_steps

        """
        pass

    def test_update_step(self):
        """Test case for update_step

        """
        pass

    def test_update_step_log(self):
        """Test case for update_step_log

        """
        pass


if __name__ == '__main__':
    unittest.main()
