# coding: utf-8
#
# Copyright (c) 2021 Target Brands, Inc. All rights reserved.

"""
    Vela server

    API for the Vela server  # noqa: E501

    OpenAPI spec version: 0.6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela
from vela.models.secret_slice import SecretSlice  # noqa: E501
from vela.rest import ApiException


class TestSecretSlice(unittest.TestCase):
    """SecretSlice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecretSlice(self):
        """Test SecretSlice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vela.models.secret_slice.SecretSlice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
