# coding: utf-8
#
# Copyright (c) 2020 Target Brands, Inc. All rights reserved.

"""
    Vela server

    API for the Vela server  # noqa: E501

    OpenAPI spec version: 0.6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela
from vela.vela.repos_api import ReposApi  # noqa: E501
from vela.rest import ApiException


class TestReposApi(unittest.TestCase):
    """ReposApi unit test stubs"""

    def setUp(self):
        self.api = ReposApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chown_repo(self):
        """Test case for chown_repo

        """
        pass

    def test_create_repo(self):
        """Test case for create_repo

        """
        pass

    def test_delete_repo(self):
        """Test case for delete_repo

        """
        pass

    def test_get_repo(self):
        """Test case for get_repo

        """
        pass

    def test_get_repos(self):
        """Test case for get_repos

        """
        pass

    def test_repair_repo(self):
        """Test case for repair_repo

        """
        pass

    def test_update_repo(self):
        """Test case for update_repo

        """
        pass


if __name__ == '__main__':
    unittest.main()
