# coding: utf-8
#
# Copyright (c) 2020 Target Brands, Inc. All rights reserved.
#
# Copyright (c) 2020 Target Brands, Inc. All rights reserved.

"""
    Vela server

    API for the Vela server  # noqa: E501

    OpenAPI spec version: 0.6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela
from vela.vela.authenticate_api import AuthenticateApi  # noqa: E501
from vela.rest import ApiException


class TestAuthenticateApi(unittest.TestCase):
    """AuthenticateApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate(self):
        """Test case for authenticate

        """
        pass


if __name__ == '__main__':
    unittest.main()
