# coding: utf-8
#
# Copyright (c) 2020 Target Brands, Inc. All rights reserved.

"""
    Vela server

    API for the Vela server  # noqa: E501

    OpenAPI spec version: 0.6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela
from vela.models.deployment import Deployment  # noqa: E501
from vela.rest import ApiException


class TestDeployment(unittest.TestCase):
    """Deployment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeployment(self):
        """Test Deployment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vela.models.deployment.Deployment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
