# coding: utf-8
#
# Copyright (c) 2021 Target Brands, Inc. All rights reserved.

# flake8: noqa
"""
    Vela server

    API for the Vela server  # noqa: E501

    OpenAPI spec version: 0.6.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from vela.models.build import Build
from vela.models.container import Container
from vela.models.container_slice import ContainerSlice
from vela.models.deployment import Deployment
from vela.models.executor import Executor
from vela.models.log import Log
from vela.models.login import Login
from vela.models.pipeline_build import PipelineBuild
from vela.models.pipeline_metadata import PipelineMetadata
from vela.models.pipeline_worker import PipelineWorker
from vela.models.repo import Repo
from vela.models.rules import Rules
from vela.models.ruleset import Ruleset
from vela.models.ruletype import Ruletype
from vela.models.secret import Secret
from vela.models.secret_slice import SecretSlice
from vela.models.service import Service
from vela.models.stage import Stage
from vela.models.stage_slice import StageSlice
from vela.models.step import Step
from vela.models.step_secret import StepSecret
from vela.models.step_secret_slice import StepSecretSlice
from vela.models.template import Template
from vela.models.ulimit import Ulimit
from vela.models.ulimit_slice import UlimitSlice
from vela.models.user import User
from vela.models.volume import Volume
from vela.models.volume_slice import VolumeSlice
from vela.models.webhook import Webhook
from vela.models.worker import Worker
